### ISSUE TITLE
pm2 give errored

### ISSUE THREAD

**Issue by kerenbir** [abhinavk99/fortnite-bot#30]
hi how to to keep bot online? i have use pm2 but status always errored.

**Comment by abhinavk99** [comment]
I think the bot might be broken because I haven't updated it in a while and I'm not planning on working on it again. Otherwise if its a pm2 issue and not a bot issue, you could try using tmux to make a terminal session that stays alive running the bot even when you log out of the server.

**Comment by kerenbir** [comment]
thank you.
